server:
  port: 8888

spring:  
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ThimmeswarnaiduM/-E-Commerce-Project
          label: master
          timeout: 5000
          clone-on-start: true
          force-pull: true

