spring:
    data:
    mongodb:
       uri: mongodb://localhost:27017/customer

  cloud:
    inetutils:
      preferred-networks:
        - 172. # Docker network range

server:
  port: 8090

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: customer-service  # Changed from ms_customer
    preferIpAddress: false
    appname: customer-service
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    mongo:
      enabled: true
    diskspace:
      enabled: true

logging:
  level:
    org.springframework.cloud: DEBUG
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
    root: INFO

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

