spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27018/customer?authSource=admin&authMechanism=SCRAM-SHA-1
      # Alternative (if using MongoDB 4.0+ with SCRAM-SHA-256):
      # uri: mongodb://admin:admin@localhost:27018/customer?authSource=admin&authMechanism=SCRAM-SHA-256

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: false

logging:
  level:
    org:
      springframework:
        web: DEBUG
      springdoc: DEBUG
