server:
  port: 8761   # Eureka server will run on port 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false   # must be kebab-case
    fetch-registry: false         # must be kebab-case
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"   # Exposes all actuator endpoints (e.g., /actuator/health, /actuator/info, etc.)
