spring:  
datasource:
      username:root
      password:mysql
       url:jdbc:mysql://localhost:3306/order_service
jpa:
  hibernate:
    ddl-auto:update
  database:
    datatype:org.hibernate.dialect.MySQL8Dialect
server:
  port:8070
application:
  customer-url:http://localhost:8090/api/v1/customers
  product-url:http://localhost:8080/api/v1/products
  payment-url:http://localhost:8081/api/v1/payments

