spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/product
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    database: postgresql
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: Initial migration
    baseline-version: 1.0
  eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: product-service  # Changed from ms_customer
    preferIpAddress: false
    appname: product-serivce
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30  
  management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    mongo:
      enabled: true
    diskspace:
      enabled: true

logging:
  level:
    org.springframework.cloud: DEBUG
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
    root: INFO

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html  

