server:
  port: 8091

spring:
  application:
    name: product-service
  config:
    import: optional:configserver:http://config-server:8888
  profiles:
    active: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/product
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none  # Ensure Flyway creates schema, or use 'update' temporarily for dev
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: Initial migration
    baseline-version: 1.0

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: product-service
    preferIpAddress: false
    appname: product-service
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    mongo:
      enabled: false  # Set to false if not using MongoDB here
    diskspace:
      enabled: true

info:
  app.name: product-service
  build.version: ${git.commit.id.abbrev}
  contact.email: e-commerce@gmail.com

logging:
  level:
    org.springframework.cloud: DEBUG
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
    root: INFO

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
